# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: caa873b4bb8487624e4881d0a417ea6e5bfc80e72a449f0a97e58e865181c90260cd15d509f2ddcf35a9d0708e79439ba64fdc08dd71530891d91a981d34467e

test:
  secret_key_base: ec22e3ddfdc6e0e288b0e9f0ead1a08ab402e27825c2552e17f1d986da27e98e4573a9e0991c1330798cd83eb58a79178e1be03105e2eba31e849d27452a5497

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
